version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workhub_bd
      MYSQL_USER: marcos
      MYSQL_PASSWORD: marcos
    ports:
      - "3306:3306"
    volumes:
      - ./bd_data:/var/lib/mysql

  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
