# Utilizar una imagen base con PHP y Apache
FROM php:8.2-apache

# Copiar el código fuente de tu proyecto al directorio del servidor web
COPY docker/apache/WorkHub /WorkHub

# Exponer el puerto 80 para que Apache pueda ser accesible desde fuera del contenedor
EXPOSE 80